name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Tests
      - uses: cypress-io/github-action@v2
      - with:
          build: npm run build
          start: npm run dev

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
