name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
